version: 0.1

storage:
  filesystem:
    rootdirectory: /registry
  delete:
    enabled: true

http:
  addr: 0.0.0.0:5000

auth:
  token:
    # external url to docker-web authentication endpoint
    realm: http://localhost:8080/api/auth
    # should be same as registry.name of registry-web
    service: mark-dev:5000
    # should be same as registry.auth.issuer of registry-web
    issuer: mark-dev
    # path to auth certificate
    rootcertbundle: /certs/domain.crt

log:
  level: info

notifications:
  endpoints:
    - name: listener
      url: http://registry-ui:8080/api/notification
      timeout: 500ms
      threshold: 5
      backoff: 1s
