registry:
  # Docker registry url
  url: http://registry:5000/v2
  # Docker registry fqdn
  name: mark:5000
  # To allow image delete, should be false
  readonly: false
  auth:
    # Enable authentication
    enabled: true
    # Token issuer
    # should equals to auth.token.issuer of docker registry
    issuer: mark
    # Private key for token signing
    # certificate used on auth.token.rootcertbundle should signed by this key
    key: /certs/domain.key
